### ISSUE TITLE
Create a full featured basic form with 3 to 6 fields

### ISSUE THREAD

**Issue by sandoche** [NEAR-labs/ui.fund3r#42]
## Features
- A few fields
- Field validation
- Submission error management
- Draft management
- Submission management
- Proposal creation

## Tasks

- [x] Create 2 components FormEdit anFormDetail
- [x] Show FormDetail only if form submitted
- [x] Add a  fields to the FormEdit
- [x] Handle the form validation
- [x] Add translations
- [x] Implement basic draft creation
- [x] Implement basic form submission
- [x] Add delay for testing https://mswjs.io/docs/api/context/delay
- [x] While loading put loading animation in the button
- [x] While loading disable the buttons & fields
- [x] Update the mock response to showw last save draft date
- [x] Show last save draft date
- [x] Skip validation to save draft
- [x] Fix lastSavedDate by setting state from parent component
- [x] Update the mock response to mark it as submitted
- [x] Fix post submit redirection
- [x] Test the Proposal creation on the blockchain
- [x] Create function for proposal creation on NEAR testnet
- [x] Add a function to create a proper nomenclature
- [x] Add a currency converter service
- [x] Update API calls & callback to return more infos to be used in the contract interaction
- [x] Add success redirection
- [x] After redirecting successfuly update state
- [x] Try to mock the submission of real data
- [x] After submitting successfully redirect to the proposal creation
- [x] After updating state call an endpoint to validate the blockchainSubmission & update the interface type
- [x] Create nearTransaction validation endpoint (?)
- [x] Implement the UI in case the form has been submitted but not the proposal
- [x] Create useGrant with context
- [x] Create useGrantStatus
- [x] Check integration with mantine UI - setErrors should work
- [x] Check zod type error responses with express - should be configured as a middleware (for direct post for example) and returns 400 error if invalid data with the errors
- [x] Create hook useGrantApplicationStatus()
- [x] Mock the response add zod to the handler with different settings so it throw errors
- [x] Implement UI for errors
- [x] Handle error from blockchain --> CANCEL TRANSACTION + FAILING TRANSACTION
- [x] Check the code / comments and todo
- [x] Change input styles to look like in the design
- [x] Fix linting
- [x] Fix type issues
- [x] Remove ignore and fix linting
- [x] Test full flow
- [x] Fix issue - Saving as draft should display last saved time
- [x] Update doc with missing info such as mocks & zod and useQuery missing
- [ ] Deploy new version

**Comment by sandoche** [comment]
https://github.com/sandoche/sputnik-dao-2-ui-reference/blob/dev-ux-improvements-and-multi-vote/src/components/dao/Dao.jsx#L1225

**Comment by sandoche** [comment]
Get the `transactionHashes` and save it

**Comment by sandoche** [comment]
Canceled transaction: `?errorCode=userRejected&errorMessage=User%2520rejected%2520transaction`
