### ISSUE TITLE
Implement the post onboarding part with milestone sending

### ISSUE THREAD

**Issue by sandoche** [NEAR-labs/ui.fund3r#82]
- [x] Define the best architecture to define which is the current milestone, and to know the state of the current milestone
- [x] Find name for "Let’s start to work" component --> DetailsMilestonesProgress
- [x] Create DetailsMilestonesProgress component
- [x] Add DetailsMilestonesProgress when the onboarding is completed
- [x] Create useMilestonesStatuses, with status list
- [x] Implement empty component with dummy data and loops
- [x] Add lines to the testing guide and mock more data and implement each
- [x] Use hook to display the right state for DetailsMilestonesProgress
- [x] Use useMilestonesStatuses in the Payment schedule
- [x] Use useMilestonesStatuses in the milestone to show the state of it ticked or not
- [x] Create a page for submitting milestones
- [x] Create the form i18n data
- [x] Create a new form type to submit milestone
- [x] Create a new mocked handler for submitting milestone
- [x] Create a new apiService to handle submitting milestone
- [x] Implement form component to submit
- [x] Handle submission to blockchain
- [x] Create mock endpoint to validate tx
- [x] Make service to validate tx
- [x] Handle tx validation
- [x] Make page to Submit to the DAO
- [x] Make sure the 5 cases are handled cf "5 Cases to handle here" by implementing 3 components
- [x] Add button in the dashboard to submit to the DAO
- [x] Add the cases to the test documentation
- [x] Mock the cases with the API
- [x] Remove the 5 Cases to handle here comment

**Comment by sandoche** [comment]
- [ ] Add locales for "Let’s start to work"
- [ ] Find name for "Let’s start to work" component
- [ ] Create "Let’s start to work" component
- [ ] Add "Let’s start to work" when the onboarding is completed

**Comment by sandoche** [comment]
When resubmitting milestone / grant application we should mark dateRejection as null
