### ISSUE TITLE
Add a "book a call state" after milestone submission

### ISSUE THREAD

**Issue by sandoche** [NEAR-labs/ui.fund3r#97]
- [x] Update MilestoneInterface with proposalNearTransactionHash, isNearProposalValid
- [x] Update MilestoneInterface  with dateInterview, dateInterviewScheduled
- [x] Update `hooks\useMilestonesStatus.ts` with INTERVIEW_SCHEDULED status
- [x] Update `StatusActionsMilestones` with Interview booking component 
- [x] Create component similar to this one `components\grant-application-details\StatusActionEvaluated.tsx`
- [x] Create mock for this API service
- [x] Create API service
- [x] Update the component
- [x] Update i18n
- [x] Update the test documentation
- [x] Change text when submit and add the time
- [x] Update `StatusActionsMilestones` with component showing the interview date
- [x] Refactor StatusActionsMilestones
- [x] Fix lint & ts
- [x] Test the calendar invite in the other part
- [x] Simplify milestone submission form
